### PR TITLE
PySCF Interface

### PR DESCRIPTION
**Pull request by matthew-hennefarth**
Adds an interface to the [PySCF](github.com/pyscf/pyscf) quantum chemistry program. Enables SA-CASSCF, MC-PDFT, and L-PDFT to be used as the on-the-fly electronic structure solver. 

Related citation: https://arxiv.org/abs/2408.05434

### CODE REVIEW

**Comment by matthew-hennefarth** [comment]
Manuscript fully published now in J. Chem. Theory Comput. https://doi.org/10.1021/acs.jctc.4c01061

**Comment by maisebastian** [comment]
Dear Matthew, 
thank you very much for the interface. I have just found the time to start merging it into SHARC 3 (and then onwards into SHARC 4). However, when I run the tests, I receive the following error:

```
Overwritten attributes  converged  of <class 'pyscf.grad.sacasscf.Gradients'>
<class 'pyscf.grad.sacasscf.Gradients'> does not have attributes  ah_level_shift ah_conv_tol conv_tol ah_start_cycle ci max_stepsize e_tot chk_ci max_cycle_micro max_cycle_macro conv_tol_grad ah_lindep ah_start_tol ah_max_cycle
Overwritten attributes  converged  of <class 'pyscf.nac.sacasscf.NonAdiabaticCouplings'>
<class 'pyscf.nac.sacasscf.NonAdiabaticCouplings'> does not have attributes  ah_level_shift ah_conv_tol conv_tol mult_ediff ah_start_cycle ci max_stepsize e_tot use_etfs chk_ci max_cycle_micro max_cycle_macro conv_tol_grad ah_lindep ah_start_tol ah_max_cycle
<class 'pyscf.mcscf.addons.StateAverageCASSCF'> does not have attributes  casdm1
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/global/mai/SHARC_3.0_tests/install/sharc/bin/SHARC_PYSCF.py", line 1283, in run_calc
    solver = gen_solver(mol, qmin)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/global/mai/SHARC_3.0_tests/install/sharc/bin/SHARC_PYSCF.py", line 1162, in gen_solver
    solver.kernel(solver.mo_coeff, solver.ci)
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/site-packages/pyscf/mcscf/mc1step.py", line 868, in kernel
    _kern(self, mo_coeff,
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/site-packages/pyscf/mcscf/mc1step.py", line 354, in kernel
    e_tot, e_cas, fcivec = casscf.casci(mo, ci0, eris, log, locals())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/site-packages/pyscf/mcscf/mc1step.py", line 885, in casci
    e_tot, e_cas, fcivec = casci.kernel(fcasci, mo_coeff, ci0, log,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/site-packages/pyscf/mcscf/casci.py", line 610, in kernel
    e_tot, fcivec = casci.fcisolver.kernel(h1eff, eri_cas, ncas, nelecas,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/site-packages/pyscf/mcscf/addons.py", line 932, in kernel
    e, c = fcibase.kernel(h1, h2, norb, nelec, ci0=ci0,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/site-packages/pyscf/fci/direct_spin1.py", line 888, in kernel
    e, c = kernel_ms1(self, h1e, eri, norb, nelec, ci0, link_index,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/site-packages/pyscf/fci/direct_spin1.py", line 658, in kernel_ms1
    e, c = fci.eig(hop, ci0, precond, tol=tol, lindep=lindep,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/site-packages/pyscf/fci/direct_spin1.py", line 856, in eig
    lib.davidson1(lambda xs: [op(x) for x in xs],
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/site-packages/pyscf/lib/linalg_helper.py", line 419, in davidson1
    xt = _qr(x0, dot, lindep)[0]
         ^^^^^^^^^^^^^^^^^^^^
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/site-packages/pyscf/lib/linalg_helper.py", line 1413, in _qr
    xs = qs = numpy.array(xs, copy=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/mai/SHARC_3.0_tests/install/sharc/bin/SHARC_PYSCF.py", line 1565, in <module>
    main()
  File "/global/mai/SHARC_3.0_tests/install/sharc/bin/SHARC_PYSCF.py", line 1547, in main
    result = run_jobs(joblist, qmin)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/mai/SHARC_3.0_tests/install/sharc/bin/SHARC_PYSCF.py", line 1346, in run_jobs
    error_codes[i], result[i] = outputs[i].get()
                                ^^^^^^^^^^^^^^^^
  File "/user/mai/anaconda/miniconda3/envs/sharc4.0/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
```

Do you have any idea what is going on? My PySCF version is 2.7.0.

Best,
Sebastian

**Comment by maisebastian** [comment]
Hi Matthew,
thanks for the hint. I am currently using PySCF 2.7.0, like you, but with numpy 1.26.4. Any idea how to resolve the problem?

Best,
Sebastian

**Comment by matthew-hennefarth** [comment]
I think I determined what was causing the issue. The PySCF CAS solver is done in the Slater determinant basis, but this is prone to spin contamination errors. I almost always use the `csf_solver` from the [`mrh`](https://github.com/matthewrhermes/mrh) package so that the calculation is done in the CSF basis, prohibiting any possible spin contamination. 

When I reload the prior calculations CI vectors with the `csf_solver` it works just fine, but when I load the prior CI vectors using the `fix_spin_` method, it crashes just as you get. I will make some corrections soon that should remedy these issues.

**Comment by matthew-hennefarth** [comment]
Also, for test 36 which is with L-PDFT (and to use any MC-PDFT method from PySCF), you will need [`pyscf-forge`](https://github.com/pyscf/pyscf-forge) to run it.

**Comment by matthew-hennefarth** [comment]
@maisebastian Try the tests 35 and 37 now. They should work. As I said above, 36 will require pyscf-forge to be installed.

**Comment by maisebastian** [comment]
Hi @matthew-hennefarth, 
thanks, that seems to have done the trick. Test 37 now ran through. I did not do test 35 yet, because I would need to recompile SHARC 3 without pysharc to enable CSDM. 

One question: Is there a way to control the charge of the molecule in the calculation? I did not see any key in the template file.

Best,
Sebastian

**Comment by maisebastian** [comment]
I have merged the interface, setup_traj.py, and the test files into main now (not directly via this merge request). Feel free to close the merge request.

**Comment by maisebastian** [comment]
I can do it.

**Comment by maisebastian** [comment]
Done

**Pull request closed without merging**
